### ISSUE TITLE
feature request: expires in amount of minutes

### ISSUE THREAD

**Issue by gileneusz** [nextapps-be/laravel-verification-code#19]
It would be nice if there would be an option to define expire time in minutes, not hours 

This will make plugin more secure - if the user has only 15-30 minutes to apply the code rather than one hour.

I tired to apply 

'expire_hours' => 0.5,

but it doesn't work as expected

**Comment by cybernerdie** [comment]
Exactly what i need at this point

**Comment by gdebrauwer** [comment]
This would be a breaking change, so it is not a change we can make on v1. In the near future, we might release a new major version that only supports PHP8, so then I will also change this to allow expiry times of less than 1 hour 🙂

**Comment by cybernerdie** [comment]
Well, I already edited the package code, from addhours to addminutes.

That's all I need.
