### ISSUE TITLE
Multibyte characters in verification code

### ISSUE THREAD

**Issue by new-user-name** [nextapps-be/laravel-verification-code#25]
Hi,
thanks a lot for a great package, it saved me a lot of time.

One minor suggestion: it does not work with Ukrainian or Russian strings, like `'characters' => 'цукенгзхфывапролджэячсмитбю'`. So I changed in `CodeGenerator`

`return $characters[rand(0, strlen($characters) - 1)];`
to
`return $characters[rand(0, count($characters) - 1)];`

and in `getCharacters`
`return $characters`
to
`return mb_str_split($characters);`

**Comment by gdebrauwer** [comment]
Can you create a PR for this?
