### ISSUE TITLE
Customise email template

### ISSUE THREAD

**Issue by bradley-varol** [nextapps-be/laravel-verification-code#35]
I'd like to be able to pass my own view when sending a code. For example:

```php
VerificationCode::send($user->email)->view('emails.verify-email', [
    'email' => $user->email,
]);

VerificationCode::send($user->email)->view('emails.reset-password', [
    'username' => $user->username,
]);
```

I am using verification codes for email verification and password resetting, so I need a separate view for each. Also, in my view file, i need the user's email address / username (as above), but this isn't available when implementing the `VerificationCodeCreatedInterface` on a custom Notification.

Is there any easy way to achieve this currently? Thanks :)

**Comment by bradley-varol** [comment]
Closing as i've just realised I can achieve this by creating a code and passing to my own notification/view!

```php
$code = VerificationCode::createFor($user->email);

$user->notify(new VerifyEmailNotification($code));
```

**Comment by gdebrauwer** [comment]
You can also just set your custom notification class in the config file of this package.
